# -*- coding: utf-8 -*-
"""NSI_retriever.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IOQw1OMZ7EYZKVPElDkCltDh-anbVbNR

# LIBRARIES
"""

import json
import httpx
import geopandas as gpd
import pandas as pd
from tqdm.notebook import tqdm

from pathlib import Path

"""# URL"""

NSI_STRUCTURES_URL = "https://nsi.sec.usace.army.mil/nsiapi/structures"

# ── Define Census tract GEOIDs ───────────────────────────────────────────────
# List all 11-digit GEOIDs to retrieve. This is the only cell you need to edit.
# GEOID = state(2) + county(3) + tract(6)
# Look up GEOIDs at: https://geocoding.geo.census.gov/geocoder/

TRACT_GEOIDS = [
 #   "36059518900",   # NY · Nassau County · Tract 5189
 #   "36059519000",   # NY · Nassau County · Tract 5190
    "36103159516"
]

"""# Census Tract"""

# ── Helper functions ──────────────────────────────────────────────────────────

TIGER_TRACT_URL = (
    "https://tigerweb.geo.census.gov/arcgis/rest/services/"
    "TIGERweb/tigerWMS_Census2020/MapServer/6/query"
)


def fetch_tract_geometry(geoid: str) -> dict:
    """
    Return a GeoJSON Feature for the Census tract identified by its 11-digit
    GEOID (state-2 + county-3 + tract-6, e.g. '36059518900').
    Queries the Census TIGER 2020 web API; no extra Python package required.
    """
    params = {
        "where": f"GEOID='{geoid}'",
        "outFields": "GEOID,NAME",
        "outSR": "4326",
        "f": "geojson",
    }
    r = httpx.get(TIGER_TRACT_URL, params=params, timeout=30, follow_redirects=True)
    r.raise_for_status()
    features = r.json().get("features", [])
    if not features:
        raise ValueError(
            f"No Census tract found for GEOID '{geoid}'. "
            "Check that state/county/tract codes are correct."
        )
    return features[0]


def fetch_nsi_by_polygon(geojson_feature: dict, label: str = "polygon",
                         timeout_s: int = 300) -> gpd.GeoDataFrame:
    """
    Download NSI structures within a polygon via the NSI POST endpoint.

    Parameters
    ----------
    geojson_feature : GeoJSON Feature dict with Polygon / MultiPolygon geometry
    label           : label shown in the progress bar
    timeout_s       : request timeout in seconds
    """
    body = {"type": "FeatureCollection", "features": [geojson_feature]}
    features = []

    with httpx.stream(
        "POST",
        NSI_STRUCTURES_URL,
        params={"fmt": "fs"},
        json=body,
        timeout=timeout_s,
        follow_redirects=True,
    ) as r:
        r.raise_for_status()
        with tqdm(unit=" structures", desc=f"  {label}", leave=True,
                  mininterval=0.5) as pbar:
            for line in r.iter_lines():
                line = line.strip()
                if line:
                    features.append(json.loads(line))
                    pbar.update(1)

    if not features:
        print("  No structures returned – check that the polygon is valid.")
        return gpd.GeoDataFrame()

    return gpd.GeoDataFrame.from_features(features, crs="EPSG:4326")


# ── Step 1: retrieve Census tract boundaries ─────────────────────────────────
# Fetches the polygon for every GEOID defined in TRACT_GEOIDS.
# Results are stored in tract_features: {geoid: GeoJSON Feature}.

tract_features = {}
for geoid in TRACT_GEOIDS:
    feature = fetch_tract_geometry(geoid)
    tract_name = feature["properties"].get("NAME", geoid)
    tract_features[geoid] = feature
    print(f"  {geoid}  →  {tract_name}")

print(f"\n{len(tract_features)} tract(s) retrieved.")

# Preview all tracts as a single GeoDataFrame
gpd.GeoDataFrame.from_features(list(tract_features.values()), crs="EPSG:4326")

"""# NSI Buildings"""

# ── Step 2: retrieve NSI structures for all Census tracts ────────────────────
# Loops over tract_features (populated in Step 1), fetches NSI structures for
# each tract, tags every row with its GEOID in the 'census_tract' column,
# and concatenates everything into a single GeoDataFrame.

gdfs = []
for geoid, feature in tract_features.items():
    gdf = fetch_nsi_by_polygon(feature, label=f"Tract {geoid}")
    gdf["census_tract"] = geoid
    gdfs.append(gdf)

nsi_tracts = gpd.GeoDataFrame(pd.concat(gdfs, ignore_index=True), crs="EPSG:4326")

print(f"\nDone. Total structures retrieved: {len(nsi_tracts):,}")
nsi_tracts

"""## NSI example upload"""

base_dir  = Path.cwd().parent / "01_Data" / "ZZ_temporary"
file_name = "nsi_tracts.gpkg"
file_path = base_dir / file_name

# ------------------------------------------------------------------
# 2) Load (read‑only) and copy for safe manipulation
# ------------------------------------------------------------------
if not file_path.exists():
    raise FileNotFoundError(f"Expected file not found:\n  {file_path}")

nsi_tracts = gpd.read_file(file_path)   # keep intact

nsi_tracts

"""# Step 1 – Retrieve OpenAddresses Data

For each county present in `nsi_tracts`, downloads the most granular available OpenAddresses dataset and stores it in `oa_data` (a dict keyed by county FIPS).

**Credentials** are loaded from `.env` in this folder — never hardcoded in the notebook.  
**Temp files** are deleted automatically as each download completes.
"""

import gzip, os, requests, tempfile
from pathlib import Path
from dotenv import load_dotenv      # pip install python-dotenv  (if needed)

# Load credentials from .env (same folder as this notebook)
load_dotenv(Path(os.getcwd()) / ".env")

_OA_API = "https://batch.openaddresses.io/api"

# State FIPS → lowercase abbreviation used in OA source paths (us/ny/..., etc.)
_STATE_FIPS_TO_ABBR = {
    "01": "al", "02": "ak", "04": "az", "05": "ar", "06": "ca",
    "08": "co", "09": "ct", "10": "de", "11": "dc", "12": "fl",
    "13": "ga", "15": "hi", "16": "id", "17": "il", "18": "in",
    "19": "ia", "20": "ks", "21": "ky", "22": "la", "23": "me",
    "24": "md", "25": "ma", "26": "mi", "27": "mn", "28": "ms",
    "29": "mo", "30": "mt", "31": "ne", "32": "nv", "33": "nh",
    "34": "nj", "35": "nm", "36": "ny", "37": "nc", "38": "nd",
    "39": "oh", "40": "ok", "41": "or", "42": "pa", "44": "ri",
    "45": "sc", "46": "sd", "47": "tn", "48": "tx", "49": "ut",
    "50": "vt", "51": "va", "53": "wa", "54": "wv", "55": "wi",
    "56": "wy",
}


# ── Authentication ────────────────────────────────────────────────────────────

def oa_login() -> str:
    """
    POST /api/login  →  returns a JWT token (valid 2 days).
    Credentials are read from .env:
        OA_USERNAME = <email or username>
        OA_PASSWORD = <password>
    """
    username = os.getenv("OA_USERNAME")
    password = os.getenv("OA_PASSWORD")

    if not username or not password:
        raise ValueError(
            "OA_USERNAME and OA_PASSWORD must be set in the .env file "
            "located in the same folder as this notebook."
        )

    r = requests.post(
        f"{_OA_API}/login",
        json={"username": username, "password": password},
        timeout=30,
    )
    r.raise_for_status()
    data = r.json()

    token = data.get("token")
    if not token:
        raise ValueError(f"Login failed – no token in response: {data}")

    print(f"Logged in as '{data.get('username', username)}'  "
          f"(level: {data.get('level', '?')}, access: {data.get('access', '?')})")
    return token


# ── Source discovery ──────────────────────────────────────────────────────────

def oa_find_all_sources(sample_points: list, state_abbr: str) -> list:
    """
    Query GET /api/data?point=…&layer=addresses for each point in sample_points
    and collect every unique OA source (deduplicated by job_id) that belongs
    to the correct state (source path starts with 'us/{state_abbr}/').

    Parameters
    ----------
    sample_points : list of (lon, lat) tuples
    state_abbr    : lowercase state abbreviation, e.g. 'ny'

    Returns
    -------
    list of unique OA catalog entries (dicts) for the correct state
    """
    prefix    = f"us/{state_abbr}/"
    seen_jobs = set()
    entries   = []

    for lon, lat in sample_points:
        r = requests.get(
            f"{_OA_API}/data",
            params={"point": f"{lon},{lat}", "layer": "addresses"},
            timeout=30,
        )
        r.raise_for_status()

        for entry in r.json():
            if not entry.get("source", "").startswith(prefix):
                continue
            job_id = entry.get("job")
            if job_id not in seen_jobs:
                seen_jobs.add(job_id)
                entries.append(entry)

    return entries


# ── Download ──────────────────────────────────────────────────────────────────

def oa_download_job(job_id: int, token: str) -> gpd.GeoDataFrame:
    """
    GET /api/job/{job_id}/output/source.geojson.gz  (requires Bearer token)

    Streams the gzip-compressed GeoJSON to a temp file, decompresses it to
    a plain .geojson, reads into a GeoDataFrame (EPSG:4326), then deletes
    both temp files.

    OA column names are fixed uppercase:
        NUMBER, STREET, UNIT, CITY, DISTRICT, REGION, POSTCODE, ID, HASH
    """
    url = f"{_OA_API}/job/{job_id}/output/source.geojson.gz"

    with tempfile.TemporaryDirectory() as tmpdir:
        gz_path      = Path(tmpdir) / f"oa_{job_id}.geojson.gz"
        geojson_path = Path(tmpdir) / f"oa_{job_id}.geojson"

        with requests.get(
            url,
            headers={"Authorization": f"Bearer {token}"},
            timeout=600,
            stream=True,
        ) as r:
            r.raise_for_status()
            with open(gz_path, "wb") as f:
                for chunk in r.iter_content(chunk_size=65536):
                    f.write(chunk)

        # Decompress: pyogrio/GDAL does not handle .geojson.gz directly
        with gzip.open(gz_path, "rb") as gz_in, open(geojson_path, "wb") as json_out:
            json_out.write(gz_in.read())

        gdf = gpd.read_file(geojson_path)
        # tmpdir (gz + geojson) auto-deleted on context exit
        return gdf


# ── Deduplication helper ──────────────────────────────────────────────────────

def _deduplicate(gdf: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
    """
    Remove duplicate address points.

    Strategy (in order of preference):
      1. HASH column  — OA content hash, unique per address record. Most
                        reliable but not always present in every dataset.
      2. Geometry WKT — two points at identical coordinates are the same
                        physical address. Used as fallback when HASH is absent.
    """
    # Case-insensitive search for a HASH column
    hash_col = next((c for c in gdf.columns if c.upper() == "HASH"), None)

    if hash_col:
        deduped = gdf.drop_duplicates(subset=[hash_col])
    else:
        deduped = gdf.copy()
        deduped["_wkt"] = deduped.geometry.to_wkt()
        deduped = deduped.drop_duplicates(subset=["_wkt"]).drop(columns=["_wkt"])

    return deduped.reset_index(drop=True)


# ── Main retrieval function ───────────────────────────────────────────────────

def retrieve_oa_for_nsi(nsi_gdf: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
    """
    Retrieve all OpenAddresses data that fully covers the NSI buildings and
    return it as a single, deduplicated GeoDataFrame.

    For each unique Census tract in nsi_gdf:
      1. Compute the bounding box of its NSI points
      2. Sample 5 points (4 corners + centroid) and query the OA API
      3. Download every unique OA source found (filtered to the correct state)
      4. Clip the result to the tract bounding box to discard addresses that
         are far outside the area of interest (e.g. from a statewide dataset)

    After processing all tracts, all per-tract GeoDataFrames are concatenated
    and deduplicated. Points that fell in more than one tract's bounding box
    (adjacent tracts with overlapping boxes) are reduced to a single row.

    Downloads are deduplicated globally: if the same OA job covers multiple
    tracts, the file is downloaded only once.

    Parameters
    ----------
    nsi_gdf : GeoDataFrame with a 'census_tract' column (11-digit GEOID).

    Returns
    -------
    GeoDataFrame  — all unique OA address points covering the NSI area (EPSG:4326)
    """
    token = oa_login()
    print()

    unique_tracts = nsi_gdf["census_tract"].unique()
    print(f"Tracts to process: {list(unique_tracts)}\n")

    job_cache    = {}   # {job_id: GeoDataFrame} – avoids duplicate downloads
    tract_slices = []   # per-tract filtered GeoDataFrames, collected for final merge

    for tract_geoid in unique_tracts:

        state_fips = tract_geoid[:2]
        state_abbr = _STATE_FIPS_TO_ABBR.get(state_fips)
        if state_abbr is None:
            print(f"Tract {tract_geoid}: unknown state FIPS '{state_fips}'. Skipping.\n")
            continue

        mask   = nsi_gdf["census_tract"] == tract_geoid
        subset = nsi_gdf.loc[mask]

        # Bounding box of the NSI points for this tract
        minx, miny, maxx, maxy = subset.total_bounds
        cx, cy = (minx + maxx) / 2, (miny + maxy) / 2

        sample_points = [
            (minx, miny), (minx, maxy),   # SW, NW
            (maxx, miny), (maxx, maxy),   # SE, NE
            (cx,   cy  ),                 # centre
        ]

        print(f"Tract {tract_geoid} ({state_abbr.upper()}):")
        print(f"  Bounding box: ({minx:.4f}, {miny:.4f}) → ({maxx:.4f}, {maxy:.4f})")
        print(f"  Querying OA API at 5 sample points …")

        entries = oa_find_all_sources(sample_points, state_abbr)

        if not entries:
            print(f"  No OA sources found for state '{state_abbr}'. Skipping.\n")
            continue

        print(f"  Found {len(entries)} unique OA source(s): "
              f"{[e['source'] for e in entries]}")

        # Download each unique source
        tract_gdfs = []
        for entry in entries:
            job_id  = entry["job"]
            source  = entry["source"]
            size_mb = (entry.get("size") or 0) / 1e6

            if job_id not in job_cache:
                print(f"  Downloading '{source}'  (job {job_id}, {size_mb:.1f} MB) …")
                job_cache[job_id] = oa_download_job(job_id, token)
                print(f"    → {len(job_cache[job_id]):,} addresses loaded. Temp file deleted.")
            else:
                print(f"  '{source}'  (job {job_id}) already in memory – reusing.")

            tract_gdfs.append(job_cache[job_id])

        # Merge sources for this tract, then clip to the tract bounding box.
        # cx[] uses coordinate indexing: retains only points whose (lon, lat)
        # falls within [minx, maxx] × [miny, maxy].
        tract_oa = (
            gpd.GeoDataFrame(pd.concat(tract_gdfs, ignore_index=True), crs="EPSG:4326")
            if len(tract_gdfs) > 1
            else tract_gdfs[0]
        )
        tract_oa = tract_oa.cx[minx:maxx, miny:maxy]
        print(f"  After bounding-box clip: {len(tract_oa):,} addresses retained.\n")

        tract_slices.append(tract_oa)

    if not tract_slices:
        print("No OA data retrieved.")
        return gpd.GeoDataFrame(crs="EPSG:4326")

    # Concatenate all per-tract slices and deduplicate
    oa_combined = gpd.GeoDataFrame(
        pd.concat(tract_slices, ignore_index=True),
        crs="EPSG:4326"
    )
    n_before = len(oa_combined)
    oa_combined = _deduplicate(oa_combined)
    n_after = len(oa_combined)

    print(f"Combined: {n_before:,} rows → {n_after:,} after deduplication "
          f"({n_before - n_after:,} duplicates removed).")

    return oa_combined

# ── Run ───────────────────────────────────────────────────────────────────────
oa_data = retrieve_oa_for_nsi(nsi_tracts)

print(f"\nTotal OA address points: {len(oa_data):,}")
oa_data.head()

"""# EXPORT"""

out_dir = Path("..") / "01_Data" / "ZZ_temporary"
out_dir.mkdir(parents=True, exist_ok=True)          # create folders if needed

out_fp = out_dir / "oa_data.gpkg"         # full file path

# write GeoPackage (use layer name if you like)
oa_data.to_file(out_fp, driver="GPKG", layer="oa_data", index=False)

print(f"Saved grid to {out_fp.resolve()}")

out_dir = Path("..") / "01_Data" / "ZZ_temporary"
out_dir.mkdir(parents=True, exist_ok=True)          # create folders if needed

out_fp = out_dir / "nsi_tracts.gpkg"         # full file path

# write GeoPackage (use layer name if you like)
nsi_tracts.to_file(out_fp, driver="GPKG", layer="nsi_tracts_grid", index=False)

print(f"Saved grid to {out_fp.resolve()}")